/*
Rudder API

Testing DirectivesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package rudder-golang

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/juhnny5/rudder-golang"
)

func Test_rudder-golang_DirectivesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DirectivesAPIService CheckDirective", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var directiveId string

		resp, httpRes, err := apiClient.DirectivesAPI.CheckDirective(context.Background(), directiveId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DirectivesAPIService CreateDirective", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DirectivesAPI.CreateDirective(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DirectivesAPIService DeleteDirective", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var directiveId string

		resp, httpRes, err := apiClient.DirectivesAPI.DeleteDirective(context.Background(), directiveId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DirectivesAPIService DirectiveDetails", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var directiveId string

		resp, httpRes, err := apiClient.DirectivesAPI.DirectiveDetails(context.Background(), directiveId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DirectivesAPIService ListDirectives", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DirectivesAPI.ListDirectives(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DirectivesAPIService UpdateDirective", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var directiveId string

		resp, httpRes, err := apiClient.DirectivesAPI.UpdateDirective(context.Background(), directiveId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
