/*
Rudder API

Testing APIInfoAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package rudder-golang

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/juhnny5/rudder-golang"
)

func Test_rudder-golang_APIInfoAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test APIInfoAPIService ApiGeneralInformations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.APIInfoAPI.ApiGeneralInformations(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIInfoAPIService ApiInformations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var endpointName string

		resp, httpRes, err := apiClient.APIInfoAPI.ApiInformations(context.Background(), endpointName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIInfoAPIService ApiSubInformations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sectionId string

		resp, httpRes, err := apiClient.APIInfoAPI.ApiSubInformations(context.Background(), sectionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
