/*
Rudder API

Testing ParametersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package rudder-golang

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/juhnny5/rudder-golang"
)

func Test_rudder-golang_ParametersAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ParametersAPIService CreateParameter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ParametersAPI.CreateParameter(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ParametersAPIService DeleteParameter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var parameterId string

		resp, httpRes, err := apiClient.ParametersAPI.DeleteParameter(context.Background(), parameterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ParametersAPIService ListParameters", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ParametersAPI.ListParameters(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ParametersAPIService ParameterDetails", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var parameterId string

		resp, httpRes, err := apiClient.ParametersAPI.ParameterDetails(context.Background(), parameterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ParametersAPIService UpdateParameter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var parameterId string

		resp, httpRes, err := apiClient.ParametersAPI.UpdateParameter(context.Background(), parameterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
